# Generated by Django 3.0.6 on 2021-01-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('title', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pending', models.BooleanField(default=True)),
                ('date_confirmed', models.DateTimeField(blank=True, default=None, null=True)),
                ('frozen_account_number', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
