# Generated by Django 3.0.6 on 2021-01-10 08:11

from django.db import migrations, models
import django.db.models.deletion
import transfers.models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_auto_20210109_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, upload_to=transfers.models.get_private_upload_path)),
                ('transfer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transfers.Transfer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
