# Generated by Django 3.0.6 on 2021-01-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_transferconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
